Repository boostcampwm-2024/web28-DDara, pull requests merged in 2024-11, with the labels that each got.

#51 [ENV][Chore] #1 : 모노 레포 설정
  .gitignore
  BackEnd/package.json
  FrontEnd/package.json
  package.json
  pnpm-workspace.yaml
Labels: 확인 요청

#90 [ENV][Chore] #1 : FE 개발환경 설정 및 Vitest, JS, TS Doc 설정
  .github/workflows/auto-assign-reviewers.yml
  .github/workflows/auto-merge.yml
  .github/workflows/request-changes.yml
  BackEnd/package.json
  BackEnd/src/hello.js
  FrontEnd/.gitignore
  FrontEnd/.storybook/main.ts
  FrontEnd/.storybook/preview.ts
  FrontEnd/index.html
  FrontEnd/package.json
  FrontEnd/postcss.config.js
  FrontEnd/public/vite.svg
  FrontEnd/src/App.css
  FrontEnd/src/App.tsx
  FrontEnd/src/assets/react.svg
  FrontEnd/src/index.css
  FrontEnd/src/main.tsx
  FrontEnd/src/stories/Button.stories.ts
  FrontEnd/src/stories/Button.tsx
  FrontEnd/src/stories/Configure.mdx
  FrontEnd/src/stories/Header.stories.ts
  FrontEnd/src/stories/Header.tsx
  FrontEnd/src/stories/Page.stories.ts
  FrontEnd/src/stories/Page.tsx
  FrontEnd/src/stories/assets/accessibility.png
  FrontEnd/src/stories/assets/accessibility.svg
  FrontEnd/src/stories/assets/addon-library.png
  FrontEnd/src/stories/assets/assets.png
  FrontEnd/src/stories/assets/avif-test-image.avif
  FrontEnd/src/stories/assets/context.png
  FrontEnd/src/stories/assets/discord.svg
  FrontEnd/src/stories/assets/docs.png
  FrontEnd/src/stories/assets/figma-plugin.png
  FrontEnd/src/stories/assets/github.svg
  FrontEnd/src/stories/assets/share.png
  FrontEnd/src/stories/assets/styling.png
  FrontEnd/src/stories/assets/testing.png
  FrontEnd/src/stories/assets/theming.png
  FrontEnd/src/stories/assets/tutorials.svg
  FrontEnd/src/stories/assets/youtube.svg
  FrontEnd/src/stories/button.css
  FrontEnd/src/stories/header.css
  FrontEnd/src/stories/page.css
  FrontEnd/src/vite-env.d.ts
  FrontEnd/tailwind.config.js
  FrontEnd/tsconfig.app.json
  FrontEnd/tsconfig.json
  FrontEnd/tsconfig.node.json
  FrontEnd/vite.config.ts
  eslint.config.mjs
  jsdoc.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  typedoc.json
Labels: 확인 요청

#91 [ENV][Fix] : Husky 버그 수정 및 동작 파일 업로드
  .github/workflows/ci.yml
  .husky/_/.gitignore
  .husky/_/applypatch-msg
  .husky/_/commit-msg
  .husky/_/h
  .husky/_/husky.sh
  .husky/_/post-applypatch
  .husky/_/post-checkout
  .husky/_/post-commit
  .husky/_/post-merge
  .husky/_/post-rewrite
  .husky/_/pre-applypatch
  .husky/_/pre-auto-gc
  .husky/_/pre-commit
  .husky/_/pre-merge-commit
  .husky/_/pre-push
  .husky/_/pre-rebase
  .husky/_/prepare-commit-msg
  .husky/pre-commit
  package.json
Labels: 확인 요청

#95 [Docs] : readme 링크 수정
  README.md
Labels: 확인 요청

#119 [ENV][BE] #82 : swagger 설치
  pnpm-lock.yaml
Labels: 확인 요청

#118 [FE][Feat] #107 : 네이버 지도 사용을 위한 로딩 코드 및 Type 추가
  frontend/index.html
  frontend/package.json
  pnpm-lock.yaml
Labels: 확인 요청

#120 [BE][Docs] #82 : swagger 설치 및 예시 적용
  backend/package.json
  backend/src/index.js
  backend/src/routes/example.js
  backend/swaggerConfig.js
  pnpm-lock.yaml
Labels: 확인 요청

#122 [BE][Feat] #44 : db 설계 및 구축
  .github/ISSUE_TEMPLATE/기능-요청-feature-request--템플릿.md
  .github/ISSUE_TEMPLATE/문서화-documentation--템플릿.md
  .github/ISSUE_TEMPLATE/버그-보고-bug-report--템플릿.md
  .github/ISSUE_TEMPLATE/작업-task--템플릿.md
  .github/pull_request_template.md
  .github/workflows/auto-assign-reviewers.yml
  .github/workflows/auto-merge.yml
  .gitignore
  .husky/_/.gitignore
  .husky/_/applypatch-msg
  .husky/_/commit-msg
  .husky/_/h
  .husky/_/husky.sh
  .husky/_/post-applypatch
  .husky/_/post-checkout
  .husky/_/post-commit
  .husky/_/post-merge
  .husky/_/post-rewrite
  .husky/_/pre-applypatch
  .husky/_/pre-auto-gc
  .husky/_/pre-commit
  .husky/_/pre-merge-commit
  .husky/_/pre-push
  .husky/_/pre-rebase
  .husky/_/prepare-commit-msg
  .husky/pre-commit
  backend/package.json
  backend/src/db.js
  backend/src/index.js
  backend/swaggerConfig.js
  frontend/package.json
  frontend/src/assets/react.svg
  pnpm-lock.yaml
Labels: 확인 요청

#129 [ENV][Fix] #1 : eslint 및 ReadMe.md 수정
  README.md
  docs/docusaurus/README.md
  docs/docusaurus/package.json
  docs/docusaurus/tsconfig.json
  eslint.config.mjs
  pnpm-lock.yaml
Labels: 확인 요청

#133 [CHORE][FE] #130 : tailwind 컬러 및 폰트 세팅
  frontend/tailwind.config.js
Labels: 확인 요청

#138 websocket 세팅 및 websocket 서버 초기화
  backend/package.json
  backend/src/constants.js
  backend/src/index.js
  backend/src/websocketServer.js
  pnpm-lock.yaml
Labels: 확인 요청

#140 [FE][Feat] #108 : 네이버 지도 API 브라우저에 출력할 수 있는 컴포넌트 구현
  eslint.config.mjs
  frontend/src/App.tsx
  frontend/src/component/maps/Map.tsx
  frontend/src/component/maps/NaverMap.tsx
  frontend/src/utils/maps/naverMap/setNaverMapObj.ts
Labels: 확인 요청

#143 [BE][Feat] : #42 : 로그인 api 구현
  backend/package.json
  backend/src/constants/constants.js
  backend/src/controllers/authController.js
  backend/src/db/db.js
  backend/src/index.js
  backend/src/middleware/validationMiddleware.js
  backend/src/repositories/userRepository.js
  backend/src/routes/authRouter.js
  backend/src/services/authService.js
  backend/src/websocketServer.js
  eslint.config.mjs
  pnpm-lock.yaml
Labels: 확인 요청

#144 [BE][Feat] : #42 : 로그인 api 구현
  backend/package.json
  backend/src/constants/constants.js
  backend/src/controllers/authController.js
  backend/src/db/db.js
  backend/src/index.js
  backend/src/middleware/validationMiddleware.js
  backend/src/repositories/userRepository.js
  backend/src/routes/authRouter.js
  backend/src/services/authService.js
  backend/src/websocketServer.js
  eslint.config.mjs
  pnpm-lock.yaml
Labels: 확인 요청

#137 [FE][FEAT] #134 : Layout Component 구현
  frontend/src/component/Layout/Footer.tsx
  frontend/src/component/Layout/Header.tsx
  frontend/src/component/Layout/Layout.tsx
  frontend/src/component/Layout/enumTypes.ts
  frontend/tailwind.config.js
Labels: 확인 요청

#146 [FE][Chore] - React Icons 추가 및 Tailwind css prettier 설정
  backend/package.json
  backend/src/constants/constants.js
  backend/src/controllers/authController.js
  backend/src/db/db.js
  backend/src/index.js
  backend/src/middleware/validationMiddleware.js
  backend/src/repositories/userRepository.js
  backend/src/routes/authRouter.js
  backend/src/services/authService.js
  backend/src/websocketServer.js
  eslint.config.mjs
  frontend/.storybook/preview.ts
  frontend/package.json
  frontend/public/vite.svg
  frontend/src/component/common/dropdown/DropdownButton.tsx
  frontend/src/stories/DropdownButton.stories.tsx
  package.json
  pnpm-lock.yaml
  prettier.config.mjs
Labels: 확인 요청

#142 [FE][Feat] #131 : router 경로들 설정
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/src/pages/AddChannel.tsx
  frontend/src/pages/DrawRoute.tsx
  frontend/src/pages/GuestView.tsx
  frontend/src/pages/HostView.tsx
  frontend/src/pages/Main.tsx
  frontend/src/pages/Register.tsx
  frontend/src/pages/UserRoute.tsx
Labels: 확인 요청

#147 [BE][Feat] : #42 : 로그인 api swagger 문서 작성
  backend/src/routes/authRouter.js
  backend/swaggerConfig.js
Labels: 확인 요청

#148 [BE][Feat] : #49 : 경로방 생성 api
  backend/package.json
  backend/src/controllers/channelController.js
  backend/src/index.js
  backend/src/repositories/channelRepository.js
  backend/src/repositories/guestRepository.js
  backend/src/routes/channelRouter.js
  backend/src/services/channelService.js
  eslint.config.mjs
  pnpm-lock.yaml
Labels: 확인 요청

#149 [BE][Feat] : swagger 문서 작성 및 수정
  backend/src/routes/channelRouter.js
  backend/swaggerConfig.js
Labels: 확인 요청

#151 [BE][Feat] #50 : 경로방 별 사용자 추가 post api
  backend/src/controllers/channelController.js
  backend/src/repositories/channelRepository.js
  backend/src/repositories/guestRepository.js
  backend/src/routes/channelRouter.js
  backend/src/routes/example.js
  backend/src/services/channelService.js
  backend/swaggerConfig.js
Labels: 확인 요청

#152 [BE][Feat] #45 : 채널 id로 채널 정보, guest 정보 get API 구현
  backend/src/controllers/channelController.js
  backend/src/repositories/channelRepository.js
  backend/src/routes/channelRouter.js
  backend/src/services/channelService.js
  backend/swaggerConfig.js
Labels: 확인 요청

#156 [BE][Feat] #46 : guest id로 guest 정보 get API 구현
  backend/src/controllers/channelController.js
  backend/src/repositories/channelRepository.js
  backend/src/routes/authRouter.js
  backend/src/routes/channelRouter.js
  backend/src/services/channelService.js
  backend/swaggerConfig.js
Labels: 확인 요청

#153 [FE][Feat] #108 : Dropdown 버튼 구현
  frontend/src/App.tsx
  frontend/src/component/common/dropdown/Dropdown.tsx
  frontend/src/component/common/dropdown/DropdownButton.tsx
  frontend/src/component/common/dropdown/DropdownItem.tsx
  frontend/src/component/common/dropdown/DropdownMenu.tsx
  frontend/src/component/common/dropdown/DropdownTrigger.tsx
  frontend/src/component/header/HeaderDropdown.tsx
  frontend/src/main.tsx
  frontend/src/stories/DropdownButton.stories.tsx
  frontend/tailwind.config.js
Labels: 확인 요청

#157 [BE][Feat] #43 : user id로 해당 user가 생성한 channel 정보 가져오기 API 구현
  backend/src/controllers/authController.js
  backend/src/controllers/channelController.js
  backend/src/repositories/channelRepository.js
  backend/src/routes/channelRouter.js
  backend/src/services/channelService.js
  backend/swaggerConfig.js
Labels: 확인 요청

#154 [FE][Feat] #13 #14 : bottomsheet와 bottomsheet 내부 content
  frontend/src/component/BottomSheet/BottomSheet.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/hooks/useBottomSheet.ts
  frontend/src/stories/BottomSheet.stories.tsx
  frontend/src/stories/Content.stories.ts
  frontend/tailwind.config.js
Labels: 확인 요청

#160 [BE][Feat] #159 : 회원가입 api 구현, [BE][Refactor] swagger 문서 tag 추가, jsdoc 추가
  backend/src/controllers/authController.js
  backend/src/controllers/channelController.js
  backend/src/index.js
  backend/src/repositories/userRepository.js
  backend/src/routes/authRouter.js
  backend/src/routes/channelRouter.js
  backend/src/services/authService.js
  backend/src/services/channelService.js
  backend/swaggerConfig.js
Labels: 확인 요청

#167 api 구현 완료 및 백엔드 배포 준비
  backend/package.json
  backend/src/controllers/authController.js
  backend/src/controllers/channelController.js
  backend/src/index.js
  backend/src/repositories/channelRepository.js
  backend/src/repositories/guestRepository.js
  backend/src/repositories/userRepository.js
  backend/src/routes/authRouter.js
  backend/src/routes/channelRouter.js
  backend/src/routes/example.js
  backend/src/services/authService.js
  backend/src/services/channelService.js
  backend/swaggerConfig.js
  eslint.config.mjs
  pnpm-lock.yaml
Labels: 확인 요청

#171 [BE][Chore] #166 : docker-compose, nginx 설정 및 백엔드 dockerfile 작성
  backend/Dockerfile
  docker-compose.yml
  nginx.conf
Labels: 확인 요청

#168 [FE][Feat] #112 : 레이아웃 상단 헤더 구현 및 공통 레이아웃 적용 (라우터 수정)
  frontend/src/App.tsx
  frontend/src/component/Layout/Header.tsx
  frontend/src/component/Layout/Layout.tsx
  frontend/src/component/common/button/Button.tsx
  frontend/src/component/common/dropdown/DropdownMenu.tsx
  frontend/src/component/header/Header.tsx
  frontend/src/component/header/HeaderBackButton.tsx
  frontend/src/component/header/HeaderMainLayout.tsx
  frontend/src/component/header/HeaderSubtitle.tsx
  frontend/src/component/header/HeaderTitle.tsx
  frontend/src/component/layout/Footer.tsx
  frontend/src/component/layout/Layout.tsx
  frontend/src/component/layout/enumTypes.ts
  frontend/src/component/layout/header/LayoutHeader.tsx
  frontend/src/component/layout/header/LayoutHeaderProvider.tsx
  frontend/src/component/maps/Map.tsx
  frontend/src/component/maps/NaverMap.tsx
  frontend/src/component/text/NoticeText.tsx
  frontend/src/main.tsx
  frontend/src/pages/GuestView.tsx
  frontend/src/routes/IndexRoutes.tsx
  frontend/tailwind.config.js
Labels: 확인 요청

#165 [FE][Feat] #30 : Main 페이지
  frontend/src/hooks/getUserLocation.ts
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#172 [FE][Feat] #4 : DrawRoute 페이지 초안
  frontend/src/component/linedrawer/Linedrawer.tsx
  frontend/src/pages/DrawRoute.tsx
Labels: 확인 요청

#173 Feature/fe/#106 add channel UI merge
  backend/package.json
  frontend/package.json
  frontend/src/component/common/InputBox.tsx
  frontend/src/component/layout/Footer.tsx
  frontend/src/component/layout/Layout.tsx
  frontend/src/component/layout/header/LayoutHeader.tsx
  frontend/src/index.css
  frontend/src/pages/AddChannel.tsx
  frontend/src/pages/DrawRoute.tsx
  frontend/src/pages/GuestView.tsx
  frontend/src/pages/Main.tsx
  frontend/src/stories/BottomSheet.stories.tsx
  frontend/tailwind.config.js
  package.json
  pnpm-lock.yaml
Labels: 확인 요청

#175 [BE][Chore] #166 : docker-compose, nginx 설정 및 백엔드 dockerfile 작성
  backend/Dockerfile
  docker-compose.yml
  nginx.conf
Labels: 확인 요청

#176 [BE][Chore] #166 : jenkinsfile 세팅
  Jenkinsfile
Labels: 확인 요청

#180 [ENV][Fix] #1 : auto-merge 정상적으로 동작안되는 문제 수정
  .github/workflows/auto-merge.yml
Labels: 확인 요청

#179 [ENV][Fix] #1 : auto-assign 라벨 바뀔때마다 되는 문제 수정
  .github/workflows/auto-assign-reviewers.yml
Labels: 확인 요청

#178 [FE][Feat][Fix][Refactor] #112 : 헤더 컴포넌트 외부에서 인자 받을 수 있는 기능 추가 및 버그 수정
  Jenkinsfile
  backend/Dockerfile
  docker-compose.yml
  frontend/src/component/common/dropdown/Dropdown.tsx
  frontend/src/component/common/dropdown/DropdownMenu.tsx
  frontend/src/component/common/dropdown/DropdownTrigger.tsx
  frontend/src/component/header/Header.tsx
  frontend/src/component/header/HeaderDropdown.tsx
  frontend/src/component/header/HeaderMainLayout.tsx
  frontend/src/component/layout/header/LayoutHeader.tsx
  frontend/src/component/layout/header/LayoutHeaderProvider.tsx
  frontend/src/pages/GuestView.tsx
  nginx.conf
  pnpm-lock.yaml
Labels: 확인 요청

#177 [FE][Feat] #59 : AuthModal 컴포넌트
  frontend/src/component/authmodal/AuthModal.tsx
  frontend/src/component/common/modal/Modal.tsx
  frontend/src/component/common/modal/ModalFooter.tsx
  frontend/src/component/common/modal/ModalHeader.tsx
  frontend/src/component/common/modal/ModalInput.tsx
  frontend/src/hooks/useModal.ts
  frontend/src/stories/AuthModal.stories.tsx
  frontend/src/stories/common/modal/Modal.stories.tsx
  frontend/src/stories/common/modal/ModalFooter.stories.tsx
  frontend/src/stories/common/modal/ModalHeader.stories.tsx
  frontend/src/stories/common/modal/ModalInput.stories.tsx
Labels: 확인 요청, 작업 완료

#200 [FE][Feat] #194 : userboard 구현
  frontend/src/component/userboard/UserBoard.tsx
  frontend/src/stories/userboard/userboard.stories.tsx
Labels: 확인 요청

#192 [FE][Fix][Docs] #145 : 플로팅 버튼 구조 변경 및 스토리북 추가
  frontend/src/component/common/FloatingButton/FloatingButton.tsx
  frontend/src/hooks/useFloatingButton.ts
  frontend/src/pages/Main.tsx
  frontend/src/stories/BottomSheet.stories.tsx
  frontend/src/stories/FloatingButton/Floatingbutton.stories.tsx
Labels: 확인 요청

#203 [BE][Feat] #40 : websocket 연결
  backend/src/index.js
  backend/src/websocketServer.js
  frontend/vite.config.ts
Labels: 확인 요청

#198 [FE][Feat] #184 : Canvas와 Map 레이어 구분 및 겹쳐서 보이게 구현
  .github/workflows/auto-assign-reviewers.yml
  .github/workflows/auto-merge.yml
  frontend/src/component/canvas/Canvas.tsx
  frontend/src/component/canvas/CanvasWithMap.tsx
  frontend/src/component/header/Header.tsx
  frontend/src/component/layout/header/LayoutHeader.tsx
  frontend/src/pages/GuestView.tsx
  frontend/src/stories/example/example.test.ts
  frontend/tailwind.config.js
Labels: 확인 요청

#205 [FE][Feat] #4 : 캔버스에 선그리기, 이동, 확대/축소 훅
  frontend/src/component/linedrawer/Linedrawer.tsx
  frontend/src/hooks/useDrawing.ts
  frontend/src/hooks/usePanning.ts
  frontend/src/hooks/useUndoRedo.ts
  frontend/src/hooks/useZoom.ts
Labels: 작업 완료

#206 [BE][Feat] #40 : websocket 연결
  backend/src/websocketServer.js
Labels: 확인 요청

#208 [BE][Feat] #40 : websocket 연결
  backend/src/index.js
  backend/src/websocketServer.js
  frontend/vite.config.ts
Labels: 확인 요청

#212 [FE][Feat] #14 : 바텀시트의 높이를 2단계 대신 자유롭게 변경할 수 있게 변경
  frontend/src/component/BottomSheet/BottomSheet.tsx
  frontend/src/component/common/modal/Modal.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/hooks/useBottomSheet.ts
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#217 [FE][Feat] #88 : 시작점과 도착점 마커를 찍기 위한 모드 추가
  frontend/src/assets/endmarker.png
  frontend/src/assets/startmarker.png
  frontend/src/component/authmodal/AuthModal.tsx
  frontend/src/component/bottomsheet/BottomSheet.tsx
  frontend/src/component/common/floatingbutton/FloatingButton.tsx
  frontend/src/component/common/modal/ModalInput.tsx
  frontend/src/component/layout/Footer.tsx
  frontend/src/component/linedrawer/Linedrawer.tsx
  frontend/src/component/markerdrawer/MarkerDrawer.tsx
  frontend/src/hooks/useDrawing.ts
  frontend/src/hooks/useMarker.ts
  frontend/src/pages/DrawRoute.tsx
  frontend/src/stories/AuthModal.stories.tsx
  frontend/src/stories/BottomSheet.stories.tsx
  frontend/src/stories/FloatingButton/Floatingbutton.stories.tsx
  frontend/src/stories/common/modal/Modal.stories.tsx
  frontend/src/stories/common/modal/ModalFooter.stories.tsx
  frontend/src/stories/common/modal/ModalHeader.stories.tsx
  frontend/src/stories/common/modal/ModalInput.stories.tsx
  frontend/src/stories/userboard/userboard.stories.tsx
Labels: 확인 요청

#216 [FE][Feat] #191 : 캔버스와 지도 겹쳐져 있을 때 동시에 이벤트 발생해서 처리하는 로직 구현
  eslint.config.mjs
  frontend/src/component/canvas/Canvas.tsx
  frontend/src/component/canvas/CanvasWithMap.tsx
  frontend/src/component/maps/Map.tsx
  frontend/src/component/maps/NaverMap.tsx
  frontend/src/component/maps/naverMapUtils.ts
  frontend/src/pages/GuestView.tsx
  frontend/src/utils/maps/naverMap/setNaverMapObj.ts
  frontend/src/utils/screen/canvasUtils.ts
Labels: 확인 요청

#218 [FE][Feat] #106 : addChannel 등 여러 페이지 수정 및 Footer Context 형식으로 변경
  frontend/src/component/header/HeaderBackButton.tsx
  frontend/src/component/layout/Footer.tsx
  frontend/src/component/layout/Layout.tsx
  frontend/src/component/layout/enumTypes.ts
  frontend/src/component/layout/footer/Footer.tsx
  frontend/src/component/layout/footer/LayoutFooter.tsx
  frontend/src/component/layout/footer/LayoutFooterProvider.tsx
  frontend/src/component/layout/header/LayoutHeaderProvider.tsx
  frontend/src/component/linedrawer/Linedrawer.tsx
  frontend/src/pages/AddChannel.tsx
  frontend/src/pages/DrawRoute.tsx
  frontend/src/pages/Main.tsx
  frontend/tailwind.config.js
Labels: 확인 요청

#223 [FE][Feat][Fix] #191 : 지도 객체 로딩 오류 수정 및 드래그 이동 이벤트 구현
  .github/workflows/auto-merge.yml
  frontend/src/component/canvas/Canvas.tsx
  frontend/src/component/canvas/CanvasWithMap.tsx
  frontend/src/component/maps/Map.tsx
  frontend/src/component/maps/NaverMap.tsx
  frontend/src/component/maps/naverMapUtils.ts
Labels: 확인 요청

#221 [BE][Feat] #219 : 헤더의 JWT 토큰으로 사용자 검증 middleware 추가
  backend/src/middleware/authenticateJWT.js
  backend/src/routes/channelRouter.js
Labels: 확인 요청

#229 [BE][Refactor] #225 : 백엔드 응답/에러 처리 공통화
  backend/src/controllers/authController.js
  backend/src/controllers/channelController.js
  backend/src/dto/errorResponse.dto.js
  backend/src/dto/response.dto.js
  backend/src/routes/authRouter.js
  backend/src/routes/channelRouter.js
  backend/src/services/channelService.js
Labels: 확인 요청

#235 [FE][Chore] #234 : 페이지 초기 세팅
  frontend/index.html
  frontend/public/assets/favicon.svg
  frontend/src/index.css
Labels: 확인 요청

#233 [FE][Fix] #155 : 폰트 적용 안되는 이슈 해결
  frontend/src/index.css
Labels: 확인 요청

#236 [FE][Feat] #224 : 캔버스와 지도 연동
  frontend/src/component/canvas/Canvas.tsx
  frontend/src/component/canvas/CanvasWithMap.tsx
  frontend/src/component/maps/Map.tsx
  frontend/src/component/maps/NaverMap.tsx
  frontend/src/hooks/usePanning.ts
Labels: 확인 요청

#228 [FE][Feat] #226 : 채널 생성 api 연동
  frontend/src/api/channel.api.ts
  frontend/src/api/dto/channel.dto.ts
Labels: 확인 요청

#227 [FE][Feat] #222 : 회원가입 api 연동
  frontend/src/api/auth.api.ts
  frontend/src/api/dto/auth.dto.ts
  frontend/src/component/authmodal/AuthModal.tsx
Labels: 확인 요청

#240 [BE][Feat] #230 : 사용자별 채널 get api response 타입 수정
  backend/src/controllers/channelController.js
  backend/swaggerConfig.js
Labels: 확인 요청

#238 [FE][Fix] #224 : Frontend 버그 수정
  frontend/src/component/canvas/CanvasWithMap.tsx
  frontend/src/pages/GuestView.tsx
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#237 [FE][Feat] #106 : add-channel 페이지 사용자 별 경로 설정 기능 구현 및 header 상수화
  frontend/src/component/header/HeaderBackButton.tsx
  frontend/src/component/layout/constant/HeaderConst.ts
  frontend/src/component/layout/enumTypes.ts
  frontend/src/component/layout/footer/Footer.tsx
  frontend/src/component/layout/footer/LayoutFooterProvider.tsx
  frontend/src/component/layout/header/LayoutHeader.tsx
  frontend/src/component/routebutton/RouteResultButton.tsx
  frontend/src/component/routebutton/RouteSettingButton.tsx
  frontend/src/context/UserContext.tsx
  frontend/src/pages/AddChannel.tsx
  frontend/src/pages/DrawRoute.tsx
  frontend/src/pages/Main.tsx
  frontend/src/routes/IndexRoutes.tsx
  frontend/src/utils/map/getAddress.ts
  frontend/src/utils/mapping/HeaderMapping.ts
Labels: 확인 요청

#245 [FE][Feat] Main.tsx 화면에서 4주차 데모를 위한 실시간 현재 위치 받아오는 기능 추가
  eslint.config.mjs
  frontend/package.json
  frontend/src/component/maps/NaverMapSample.tsx
  frontend/src/constants.ts
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#247 [FE][Refactor] #224 : 지도 컴포넌트 리팩토링
  frontend/src/component/maps/Map.tsx
  frontend/src/component/maps/Map.types.ts
  frontend/src/component/maps/NaverMap.tsx
  frontend/src/component/maps/mapUtils.ts
  frontend/src/component/maps/naverMapUtils.ts
Labels: 확인 요청

#251 [FE][Refactor] #224 : CanvasWithMap 이벤트 함수를 훅으로 분리
  .github/workflows/ci.yml
  frontend/src/component/canvas/Canvas.tsx
  frontend/src/component/canvas/CanvasWithMap.tsx
  frontend/src/component/canvas/useEventHandlers.tsx
Labels: 확인 요청

#252 [FE][Feat] #249 : 지도와 캔버스 연동 및 완성
  frontend/src/App.css
  frontend/src/api/client.api.ts
  frontend/src/component/authmodal/AuthModal.tsx
  frontend/src/component/canvas/Canvas.tsx
  frontend/src/component/canvas/CanvasWithMap.tsx
  frontend/src/component/canvas/useEventHandlers.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/maps/Canvas.tsx
  frontend/src/component/maps/Map.tsx
  frontend/src/component/maps/MapCanvas.tsx
  frontend/src/component/maps/NaverMap.tsx
  frontend/src/component/maps/NaverMapSample.tsx
  frontend/src/component/maps/naverMapUtils.ts
  frontend/src/index.css
  frontend/src/lib/constants/canvasConstants.ts
  frontend/src/lib/constants/commonConstants.ts
  frontend/src/lib/constants/mapConstants.ts
  frontend/src/lib/types/canvasInterface.ts
  frontend/src/pages/GuestView.tsx
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#254 [FE][Feat] #253 : 채널 추가 지도-캔버스 연동 화면 표시
  frontend/src/component/linedrawer/Linedrawer.tsx
  frontend/src/component/maps/Canvas.tsx
  frontend/src/component/maps/MapCanvas.tsx
  frontend/src/hooks/useFloatingButton.ts
  frontend/src/hooks/useUndoRedo.ts
  frontend/src/lib/constants/canvasConstants.ts
  frontend/src/lib/types/canvasInterface.ts
  frontend/src/pages/DrawRoute.tsx
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#256 [FE][Refactor] #255 : 불필요해진 파일들 제거 및 파일명 변경
  frontend/src/component/canvas/Canvas.tsx
  frontend/src/component/canvas/CanvasWithMap.tsx
  frontend/src/component/canvas/useEventHandlers.tsx
  frontend/src/component/canvasWithMap/MapCanvasForDraw.tsx
  frontend/src/component/canvasWithMap/MapProviderForDraw.tsx
  frontend/src/component/linedrawer/Linedrawer.tsx
  frontend/src/component/maps/Map.tsx
  frontend/src/component/maps/Map.types.ts
  frontend/src/component/maps/NaverMap.tsx
  frontend/src/component/maps/NaverMapSample.tsx
  frontend/src/component/maps/mapUtils.ts
  frontend/src/component/maps/naverMapUtils.ts
  frontend/src/hooks/useDrawing.ts
  frontend/src/hooks/usePanning.ts
  frontend/src/hooks/useZoom.ts
  frontend/src/pages/DrawRoute.tsx
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#259 [FE][Feat] #258 : 지도-캔버스 연동된 화면 (보기 전용)
  frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
  frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapCanvasForDraw.tsx
  frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapProviderForDraw.tsx
  frontend/src/lib/constants/mapConstants.ts
  frontend/src/lib/types/canvasInterface.ts
  frontend/src/pages/DrawRoute.tsx
Labels: 확인 요청

#261 [FE][Feat] #112 : 통신 로직 및 받아온 데이터 드랍다운에 반영
  frontend/src/api/auth.api.ts
  frontend/src/api/channel.api.ts
  frontend/src/component/common/dropdown/DropdownItem.tsx
  frontend/src/component/header/HeaderDropdown.tsx
  frontend/src/component/layout/header/LayoutHeader.tsx
  frontend/src/pages/HostView.tsx
  frontend/src/types/channel.types.ts
Labels: 확인 요청

#262 [FE][Feat] #260 : 홈화면에 지도-캔버스 연동된 화면 노출
  frontend/index.html
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/index.css
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#265 [BE][Chore] #242 : 4주차 배포를 위한 nginx 세팅
  nginx.conf
Labels: 확인 요청

#268 [BE][Chore] #242 : 4주차 배포를 위한 세팅
  backend/package.json
  backend/src/websocketServer.js
  docker-compose.yml
  frontend/Dockerfile
Labels: 확인 요청

#270 Feature/fe/search
  frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapCanvasForDraw.tsx
  frontend/src/component/header/Header.tsx
  frontend/src/component/routebutton/RouteResultButton.tsx
  frontend/src/component/searchbox/SearchBox.tsx
  frontend/src/pages/DrawRoute.tsx
Labels: 확인 요청

#282 [BE][Chore] FE 컨테이너 Workdir 생성 안되는 문제 해결
  backend/Dockerfile
  docker-compose.yml
  frontend/Dockerfile
  nginx.conf
Labels: 확인 요청

#273 [FE][Feat] #14 : bottomsheet 관련 로그인, 회원가입
  frontend/src/api/dto/auth.dto.ts
  frontend/src/api/dto/channel.dto.ts
  frontend/src/component/authmodal/AuthModal.tsx
  frontend/src/component/bottomsheet/BottomSheet.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/pages/Main.tsx
  frontend/tailwind.config.js
Labels: 확인 요청

#283 nginx 에러 해결을 위한 Dockerfile, docker-compose, nginx 파일 수정
  backend/Dockerfile
  docker-compose.yml
  frontend/Dockerfile
  nginx.conf
Labels: 확인 요청

#275 [FE][Feat] #241 : createChannel API 연동 성공
  frontend/src/api/dto/channel.dto.ts
  frontend/src/component/routebutton/RouteResultButton.tsx
  frontend/src/component/searchbox/SearchBox.tsx
  frontend/src/component/tooldescription/ToolDescription.tsx
  frontend/src/pages/AddChannel.tsx
  frontend/src/pages/DrawRoute.tsx
Labels: 확인 요청

#284 [BE][Chore] volumes로 app 디렉토리 공유하도록 변경
  backend/Dockerfile
  docker-compose.yml
  frontend/Dockerfile
Labels: 확인 요청

#269 [FE][Feat] #264 : 서버에서 받아온 데이터를 지도 및 캔버스와 연동
  frontend/src/api/channel.api.ts
  frontend/src/api/dto/channel.dto.ts
  frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
  frontend/src/lib/types/canvasInterface.ts
  frontend/src/pages/HostView.tsx
  frontend/src/types/channel.types.ts
Labels: 확인 요청

#272 [BE][Feat] #271 : 사용자의 채널 리스트 가져올 때 게스트 인원수도 가져오기
  backend/src/repositories/channelRepository.js
  backend/swaggerConfig.js
Labels: 확인 요청

#276 지도 가져올 때 로딩 화면 추가 (로딩 스피너로 대체)
  frontend/src/App.css
  frontend/src/component/common/loadingSpinner/LoadingSpinner.tsx
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#287 [FE][Feat] #286 : 데스크탑 접속시 모바일 접속 유도
  frontend/src/App.css
  frontend/src/App.tsx
Labels: 확인 요청

#285 [BE][Chore] FE 배포 완료
  backend/src/repositories/channelRepository.js
  backend/src/services/authService.js
  backend/swaggerConfig.js
  docker-compose.yml
Labels: 확인 요청

#290 [FE][Fix] #59 : DTO 구조 수정 및 pw input type 수정
  frontend/src/api/dto/auth.dto.ts
  frontend/src/component/authmodal/AuthModal.tsx
  frontend/src/component/common/modal/ModalInput.tsx
Labels: 확인 요청

#288 [FE][Feature] #280 : HostView, GuestView 구현 및 업데이트
  frontend/package.json
  frontend/public/assets/icons/Assistant Navigation Icon.svg
  frontend/public/assets/icons/Person Pin Icon.svg
  frontend/public/assets/icons/flag2.svg
  frontend/public/assets/icons/location_on.svg
  frontend/src/api/channel.api.ts
  frontend/src/component/IconGuide/GuestMarker.tsx
  frontend/src/component/IconGuide/HostMarker.tsx
  frontend/src/component/common/dropdown/DropdownItem.tsx
  frontend/src/component/header/Header.tsx
  frontend/src/component/header/HeaderDropdown.tsx
  frontend/src/component/header/HeaderMainLayout.tsx
  frontend/src/component/layout/header/LayoutHeaderProvider.tsx
  frontend/src/pages/GuestView.tsx
  frontend/src/pages/HostView.tsx
  frontend/src/types/channel.types.ts
  pnpm-lock.yaml
Labels: 확인 요청

#291 [FE][Feat] #286 : 데스크탑 접속시 모바일 접속 유도 병합 과정 충돌 해결
  frontend/src/App.css
Labels: 확인 요청

#293 [FE][Feat] build 오류 제거
  frontend/src/api/dto/channel.dto.ts
Labels: 확인 요청

#294 [FE][Fix] 머지 과정에서 발생한 충돌 해결
  frontend/src/api/dto/channel.dto.ts
Labels: 확인 요청

#296 [FE][ENV] #295 : 백엔드 api 주소 변경
  frontend/src/lib/constants/commonConstants.ts
Labels: 확인 요청

#297 [FE][Feat] #59 : 바텀시트 전체에서 클릭시 로그인 모달 띄움
  frontend/src/component/bottomsheet/BottomSheet.tsx
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#299 [BE][Feat] #298 : 채널 get api 응답 형식에 location title 항목 추가
  backend/src/repositories/channelRepository.js
  backend/swaggerConfig.js
Labels: 확인 요청

#300 [BE][Feat] #298 : 채널 get api 응답 형식에 location title 항목 추가
  backend/src/repositories/channelRepository.js
  backend/swaggerConfig.js
Labels: 확인 요청

#304 [FE][Feat] #302 : 로그인해야 접속할 수 있는 url 접속시 접속이 불가능하도록 차단
  eslint.config.mjs
  frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
  frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapCanvasForDraw.tsx
  frontend/src/component/common/alert/Alert.tsx
  frontend/src/routes/IndexRoutes.tsx
  frontend/src/routes/RequireAuth.tsx
Labels: 확인 요청

#305 [FE][Refactor] #303 : 사용하지 않는 routes 및 파일 제거
  frontend/src/pages/Register.tsx
  frontend/src/pages/UserRoute.tsx
  frontend/src/routes/IndexRoutes.tsx
Labels: 확인 요청

#307 [FE][Refactor] #306 : 로딩 스피너 텍스트 제거
  frontend/src/component/common/loadingSpinner/LoadingSpinner.tsx
Labels: 확인 요청

#309 [FE][Feat] 수정하기 페이지 구현 및 링크 복사 구현
  backend/src/repositories/channelRepository.js
  backend/swaggerConfig.js
  frontend/src/api/channel.api.ts
  frontend/src/component/bottomsheet/BottomSheet.tsx
  frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
  frontend/src/component/common/dropdown/DropdownItem.tsx
  frontend/src/component/common/dropdown/DropdownMenu.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/layout/constant/HeaderConst.ts
  frontend/src/component/routebutton/RouteResultButton.tsx
  frontend/src/component/routebutton/RouteSettingButton.tsx
  frontend/src/component/routebutton/enum.ts
  frontend/src/context/ChannelContext.tsx
  frontend/src/context/CurrentUserContext.tsx
  frontend/src/context/UserContext.tsx
  frontend/src/pages/AddChannel.tsx
  frontend/src/pages/DrawRoute.tsx
  frontend/src/pages/Main.tsx
  frontend/src/pages/UpdateChannel.tsx
  frontend/src/routes/IndexRoutes.tsx
Labels: 확인 요청

#312 [FE][Fix] #311 : Alert progress bar 배포시 적용되지 않는 문제 해결
  frontend/src/component/common/alert/Alert.tsx
  frontend/src/routes/RequireAuth.tsx
Labels: 확인 요청

#313 [FE][Feat] #241 : 스타일 변경 및 채널 상태 로직 변경
  frontend/src/component/content/Content.tsx
  frontend/src/component/routebutton/RouteResultButton.tsx
  frontend/src/component/routebutton/RouteSettingButton.tsx
  frontend/src/pages/AddChannel.tsx
  frontend/src/pages/ChannelInfoPage.tsx
  frontend/src/pages/DrawRoute.tsx
  frontend/src/routes/IndexRoutes.tsx
Labels: 확인 요청

#315 [FE][Feat] #314 : 마커 설정 시 줌 기능 구현
  frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapCanvasForDraw.tsx
  frontend/src/component/routebutton/RouteResultButton.tsx
Labels: 확인 요청

#310 [FE][Design] #14 : 디자인, 기능 수정
  frontend/public/assets/icons/endmarker.svg
  frontend/public/assets/icons/guestlocationmarker.svg
  frontend/public/assets/icons/mylocation.svg
  frontend/public/assets/icons/startmarker.svg
  frontend/src/assets/endmarker.png
  frontend/src/assets/endmarker.svg
  frontend/src/assets/guestlocationmarker.svg
  frontend/src/assets/mylocation.svg
  frontend/src/assets/startmarker.png
  frontend/src/assets/startmarker.svg
  frontend/src/component/bottomsheet/BottomSheet.tsx
  frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
  frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapCanvasForDraw.tsx
  frontend/src/component/zoomslider/ZoomSlider.tsx
  frontend/src/hooks/useCanvasInteraction.ts
  frontend/src/hooks/useRedraw.ts
  frontend/src/pages/Main.tsx
  frontend/tailwind.config.js
Labels: 확인 요청

#317 5주차 3차 배포
  frontend/public/assets/icons/endmarker.svg
  frontend/public/assets/icons/guestlocationmarker.svg
  frontend/public/assets/icons/mylocation.svg
  frontend/public/assets/icons/startmarker.svg
  frontend/src/assets/endmarker.png
  frontend/src/assets/endmarker.svg
  frontend/src/assets/guestlocationmarker.svg
  frontend/src/assets/mylocation.svg
  frontend/src/assets/startmarker.png
  frontend/src/assets/startmarker.svg
  frontend/src/component/IconGuide/HostMarker.tsx
  frontend/src/component/bottomsheet/BottomSheet.tsx
  frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
  frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapCanvasForDraw.tsx
  frontend/src/component/common/alert/Alert.tsx
  frontend/src/component/common/dropdown/DropdownItem.tsx
  frontend/src/component/common/dropdown/DropdownMenu.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/header/HeaderDropdown.tsx
  frontend/src/component/header/HeaderDropdownProvider.tsx
  frontend/src/component/header/HeaderMainLayout.tsx
  frontend/src/component/layout/Layout.tsx
  frontend/src/component/layout/header/LayoutHeader.tsx
  frontend/src/component/layout/header/LayoutHeaderProvider.tsx
  frontend/src/component/routebutton/RouteResultButton.tsx
  frontend/src/component/routebutton/RouteSettingButton.tsx
  frontend/src/component/zoomslider/ZoomSlider.tsx
  frontend/src/hooks/useCanvasInteraction.ts
  frontend/src/hooks/useRedraw.ts
  frontend/src/pages/AddChannel.tsx
  frontend/src/pages/ChannelInfoPage.tsx
  frontend/src/pages/DrawRoute.tsx
  frontend/src/pages/HostView.tsx
  frontend/src/pages/Main.tsx
  frontend/src/routes/IndexRoutes.tsx
  frontend/src/routes/RequireAuth.tsx
  frontend/tailwind.config.js
Labels: 확인 요청

#318 [FE][Feature] #301 : HostView, GuestView 피젯스피너 추가
  frontend/src/component/IconGuide/GuestMarker.tsx
  frontend/src/pages/GuestView.tsx
  frontend/src/pages/HostView.tsx
Labels: 확인 요청

#322 [FE][Feat] #321 : 현재 위치 추적이 실시간을 되지 않는 문제 해결
  frontend/src/hooks/getUserLocation.ts
Labels: 확인 요청

#323 5주차 4차 배포
  frontend/src/component/IconGuide/GuestMarker.tsx
  frontend/src/hooks/getUserLocation.ts
  frontend/src/pages/GuestView.tsx
  frontend/src/pages/HostView.tsx
Labels: 확인 요청

#330 [BE][Fix] #329 : hostview, guestview에서 접속한 경우 각각에 대한 socket 설정 수정
  backend/src/websocketServer.js
Labels: 확인 요청

#328 [FE][Feat] : 바텀시트, 메인페이지 QA 작업
  frontend/src/component/bottomsheet/BottomSheet.tsx
  frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/zoomslider/ZoomSlider.tsx
  frontend/src/hooks/useRedraw.ts
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#331 [BE][Fix] #329 : hostview, guestview에서 접속한 경우 각각에 대한 socket 설정 수정
  backend/src/websocketServer.js
Labels: 확인 요청

#325 [FE][Feat] addGuest 페이지 및 기능 구현
  frontend/src/api/channel.api.ts
  frontend/src/api/dto/channel.dto.ts
  frontend/src/component/common/InputBox.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/layout/constant/HeaderConst.ts
  frontend/src/component/routebutton/RouteResultButton.tsx
  frontend/src/context/UserContext.tsx
  frontend/src/pages/AddChannel.tsx
  frontend/src/pages/AddGuestPage.tsx
  frontend/src/pages/ChannelInfoPage.tsx
  frontend/src/pages/DrawRoute.tsx
  frontend/src/routes/IndexRoutes.tsx
  frontend/src/utils/mapping/HeaderMapping.ts
Labels: 확인 요청

#326 [FE][Feat] #324 : 정의되지 않은 경로에 대한 예외 처리
  frontend/src/routes/AlertUndefinedURL.tsx
  frontend/src/routes/IndexRoutes.tsx
Labels: 확인 요청

#335 5주차 5차 배포
  frontend/src/api/channel.api.ts
  frontend/src/api/dto/channel.dto.ts
  frontend/src/component/bottomsheet/BottomSheet.tsx
  frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
  frontend/src/component/common/InputBox.tsx
  frontend/src/component/content/Content.tsx
  frontend/src/component/header/HeaderDropdown.tsx
  frontend/src/component/layout/constant/HeaderConst.ts
  frontend/src/component/routebutton/RouteResultButton.tsx
  frontend/src/component/zoomslider/ZoomSlider.tsx
  frontend/src/context/UserContext.tsx
  frontend/src/hooks/useFloatingButton.ts
  frontend/src/hooks/useRedraw.ts
  frontend/src/pages/AddChannel.tsx
  frontend/src/pages/AddGuestPage.tsx
  frontend/src/pages/ChannelInfoPage.tsx
  frontend/src/pages/DrawRoute.tsx
  frontend/src/pages/Main.tsx
  frontend/src/routes/AlertUndefinedURL.tsx
  frontend/src/routes/IndexRoutes.tsx
  frontend/src/utils/mapping/HeaderMapping.ts
Labels: 확인 요청

#341 [FE][Feat] #336 : 게스트 정보 조회 API 응답 형식 틀린 문제 해결
  backend/src/websocketServer.js
  frontend/src/api/channel.api.ts
  frontend/src/api/dto/channel.dto.ts
Labels: 확인 요청

#344 [BE][Fix] #337 : hostview, guestview에 대한 websocket 오류 발생 해결
  backend/src/websocketServer.js
Labels: 확인 요청

#345 [FE][Fix] 배포를 위한 검색 API URL 수정
  frontend/src/component/searchbox/SearchBox.tsx
Labels: 확인 요청

#347 [FE][Feat] #339 : 지도에 사용자 실시간 방향 표시
  frontend/public/assets/icons/guestlocationmarker.svg
  frontend/src/api/channel.api.ts
  frontend/src/api/dto/channel.dto.ts
  frontend/src/assets/character1.png
  frontend/src/assets/character2.png
  frontend/src/assets/character3.png
  frontend/src/assets/character4.png
  frontend/src/assets/character5.png
  frontend/src/assets/character6.png
  frontend/src/assets/guestlocationmarker.svg
  frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
  frontend/src/hooks/getUserLocation.ts
  frontend/src/hooks/useRedraw.ts
  frontend/src/hooks/useSocket.ts
  frontend/src/lib/types/canvasInterface.ts
  frontend/src/pages/GuestView.tsx
  frontend/src/pages/HostView.tsx
  frontend/src/pages/Main.tsx
Labels: 확인 요청

#346 [FE][Feat] #338 : 호스트, 게스트 이미지 캐릭터로 변경
  frontend/public/assets/icons/guestlocationmarker.svg
  frontend/src/assets/character1.png
  frontend/src/assets/character2.png
  frontend/src/assets/character3.png
  frontend/src/assets/character4.png
  frontend/src/assets/character5.png
  frontend/src/assets/character6.png
  frontend/src/assets/guestlocationmarker.svg
  frontend/src/hooks/useRedraw.ts
  frontend/src/pages/GuestView.tsx
Labels: 확인 요청

#348 5주차 6차 배포 (FE)
  frontend/src/component/searchbox/SearchBox.tsx
  frontend/src/lib/types/canvasInterface.ts
  frontend/src/pages/HostView.tsx
Labels: 확인 요청

#349 5주차 6차 배포 (BE)
  backend/src/websocketServer.js
Labels: 확인 요청
